{
global:
    xlogger_*;
    __xlogger_*;

  
    *appender_*;
    Java_*;
    *LogLogic*;
    *LogBuffer*;
  
    JNI_OnLoad; 
    Java_com*;

    *mars*xlog*NewXloggerInstance*;
    *mars*xlog*GetXloggerInstance*;
    *mars*xlog*ReleaseXloggerInstance*;
    *mars*xlog*XloggerWrite*;
    *mars*xlog*IsEnabledFor*;
    *mars*xlog*GetLevel*;
    *mars*xlog*SetLevel*;
    *mars*xlog*SetAppenderMode*;
    *mars*xlog*Flush*;
    *mars*xlog*FlushAll*;
    *mars*xlog*SetConsoleLogOpen*;
    *mars*xlog*SetMaxFileSize*;
    *mars*xlog*SetMaxAliveTime*;

local:
    *;
};
