apply plugin: 'com.android.library'

apply from: rootProject.file('gradle/WeChatPublish.gradle')

group PROJ_GROUP
version PROJ_VERSION
artifactId = PROJ_ARTIFACTID

android {
    namespace "com.tencent.mars.xlog"
    compileSdkVersion 34
    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 29
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
    }
    sourceSets {
        main {
            java {
                srcDir "src/main/java"
            }
            jni {
                srcDir "src/main/jni"
            }
            jniLibs {
                srcDir "libs"
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        release {
            proguardFile 'proguard-rules.pro'
        }
    }
}
